apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    cluster.x-k8s.io/provider: infrastructure-openstack
    helm.sh/chart: '{{ .Chart.Name }}'
  name: capo-serving-cert
  namespace: '{{ .Release.Namespace }}'
spec:
  dnsNames:
  - capo-webhook-service.{{ .Release.Namespace }}.svc
  - capo-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-thgice
  secretName: capo-webhook-service-cert
