apiVersion: v2
appVersion: "[[ .Version ]]"
name: cluster-api-provider-openstack
description: Helm chart for cluster-api-provider-openstack.
home: https://github.com/giantswarm/cluster-api-provider-openstack-app
version: "[[ .Version ]]"
icon: https://s.giantswarm.io/app-icons/openstack/1/light.svg
