---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: capo-serving-cert
  namespace: capo-system
spec:
  dnsNames:
    - capo-webhook-service.{{ .Release.Namespace }}.svc
    - capo-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-thgice
  secretName: capo-webhook-service-cert
